apiVersion: link.aioutfitter.com/v1alpha1
kind: Organization
metadata:
  name: mail-loop-demo
spec:
  displayName: Mail loop demo
  agentCatalogs:
    - name: link-operator-agents
      github: ncrmro/link-operator
      revision: f69338a4b1e7c3db0dcb4d0383beb22cd95448aa
      path: .agents
