apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../code/operator/config/default
images:
  - name: controller
    newName: example.invalid/link-operator
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --agent-image=example.invalid/link-agent@sha256:0000000000000000000000000000000000000000000000000000000000000000
