apiVersion: link.aioutfitter.com/v1alpha1
kind: Organization
metadata:
  name: nonprod-channels
spec:
  displayName: Nonprod channel agents
  agentCatalogs:
    - name: unsupervised-agents
      github: Unsupervisedcom/unsupervised-main
      revision: 796cddcbdc05f730db03ed819bc4edf5a43bc8db
      path: .agents
