apiVersion: aioutfitter.com/v1alpha1
kind: Organization
metadata:
  name: nonprod-channels
spec:
  displayName: Nonprod channel agents
  agentCatalogs:
    - name: agent-operator-agents
      github: ai-outfitter/agent-operator
      revision: d5ffe5dd05c10796f6793493aab06740d0fc32ff
      path: code/agent/agents-catalog
