apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../operator.yaml]
images:
  - name: workspace-operator
    newName: git.ncrmro.com/ncrmro/workspace-operator
    newTag: dev-20260930-2
patches:
  - target: {kind: Deployment, name: workspace-operator}
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/4
        value: --workspace-image=git.ncrmro.com/ncrmro/outfitter-workspace:dev-20260930-4
